### PR TITLE
seek when click at cuepoint

### PR DESCRIPTION
**Pull request by fracz**
Credits go to [noppolp](https://github.com/noppolp/videogular-cuepoints/commit/cf927092e5cf923eaaacf7fe1918e89caad7dcef).

### CODE REVIEW

**Comment by HarryCutts** [comment]
Thanks for the PR! For future reference, the main repository is now [HarryCutts/videogular-cuepoints](https://github.com/HarryCutts/videogular-cuepoints/) (I'll merge this PR into there too).

**Comment by fracz** [comment]
It's not clear because this is the "main" repo and the `HarryCutts/videogular-cuepoints` is a fork. You could add some clarification to the README here.

**Comment by fracz** [comment]
Also, the "issues" tab/feature is not enabled in the `HarryCutts/videogular-cuepoints`.

**Comment by HarryCutts** [comment]
I've added a comment in the README and enabled issues in the new repository.

**Pull request merged**
